spring.application.name=BloodDonationApplication

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:mysql://localhost:3306/blooddb
spring.datasource.username=root
spring.datasource.password=Indhu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true